In [2]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense

In [3]:
#load the data
(X_train,y_train),(X_test,y_test) = mnist.load_data()

11490434/11490434 [==============================] - 32s 3us/step


In [6]:
#reshape data
X_train= X_train.reshape((X_train.shape[0]), X_train.shape[1], X_train.shape[2],1)
X_test = X_test.reshape((X_test.shape[0]),X_test.shape[2],X_test.shape[2],1)

In [7]:
print(X_train.shape)

(60000, 28, 28, 1)


In [8]:
print(X_test.shape)

(10000, 28, 28, 1)


In [9]:
#normalize pixel values
X_train = X_train/255
X_test = X_test/255

In [11]:
print(X_train)
print(X_test)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [14]:
print(y_train)
print(y_test)

[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [15]:
model = Sequential()

In [16]:
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)))

In [17]:
model.add(MaxPool2D(2,2))

In [18]:
model.add(Flatten())
model.add(Dense(100,activation='relu'))

In [19]:
#adding output layer
model.add(Dense(10,activation='softmax'))

In [20]:
model.compile(loss= 'sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [21]:
model.fit(X_train,y_train,epochs=10)

Epoch 1/10


1875/1875 [==============================] - 10s 5ms/step - loss: 0.1558 - accuracy: 0.9541
Epoch 2/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0527 - accuracy: 0.9842
Epoch 3/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0345 - accuracy: 0.9892
Epoch 4/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0219 - accuracy: 0.9931
Epoch 5/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0148 - accuracy: 0.9954
Epoch 6/10
1875/1875 [==============================] - 8s 5ms/step - loss: 0.0122 - accuracy: 0.9962
Epoch 7/10
1875/1875 [==============================] - 8s 5ms/step - loss: 0.0081 - accuracy: 0.9973
Epoch 8/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0066 - accuracy: 0.9978
Epoch 9/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0063 - accuracy: 0.9979
Epoch 10/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.

In [22]:
model.evaluate(X_test,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0498 - accuracy: 0.9886


[0.049771662801504135, 0.9886000156402588]